
version: '3'

services:
  nya-services:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data:rw
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - nya-network

networks:
  nya-network:
    driver: bridge
